/**
 * base on eslint v4.3.0
 */
module.exports = {
  // Possible Errors
  'for-direction': 'error',
  'getter-return': 'warn',
  'no-await-in-loop': 'error',
  'no-compare-neg-zero': 'error',
  // 'no-cond-assign': 'off',
  'no-console': 'off',
  // 'no-constant-condition': 'off',
  // 'no-control-regex': 'off',
  // 'no-debugger': 'off',
  // 'no-dupe-args': 'off',
  // 'no-dupe-keys': 'off',
  // 'no-duplicate-case': 'off',
  // 'no-empty': 'off',
  // 'no-empty-character-class': 'off',
  // 'no-ex-assign': 'off',
  // 'no-extra-boolean-cast': 'off',
  'no-extra-parens': ['error', 'all', { ignoreJSX: 'multi-line' }],
  // 'no-extra-semi': 'off',
  // 'no-func-assign': 'off',
  // 'no-inner-declarations': 'off',
  // 'no-invalid-regexp': 'off',
  // 'no-irregular-whitespace': 'off',
  // 'no-obj-calls': 'off',
  'no-prototype-builtins': 'off',
  // 'no-regex-spaces': 'off',
  // 'no-sparse-arrays': 'off',
  'no-template-curly-in-string': 'off',
  // 'no-unexpected-multiline': 'off',
  // 'no-unreachable': 'off',
  // 'no-unsafe-finally': 'off',
  // 'no-unsafe-negation': 'off',
  // 'use-isnan': 'off',
  'valid-jsdoc': 'off',
  // 'valid-typeof': 'off',

  // Best Practices
  'accessor-pairs': 'off',
  'array-callback-return': 'error',
  'block-scoped-var': 'error',
  'class-methods-use-this': 'off',
  'complexity': 'off',
  'consistent-return': 'off',
  'curly': ['error', 'all'],
  'default-case': 'off',
  // 'dot-location': 'off',
  // 'dot-notation': 'off',
  'eqeqeq': 'error',
  'guard-for-in': 'error',
  'no-alert': 'off',
  'no-caller': 'error',
  // 'no-case-declarations': 'off',
  'no-div-regex': 'off',
  'no-else-return': 'error',
  'no-empty-function': ['error', { 'allow': ['arrowFunctions', 'functions', 'methods'] }],
  // 'no-empty-pattern': 'off',
  'no-eq-null': 'off',
  'no-eval': 'error',
  'no-extend-native': 'error',
  // 'no-extra-bind': 'off',
  'no-extra-label': 'off',
  // 'no-fallthrough': 'off',
  'no-floating-decimal': 'error',
  'no-global-assign': 'warn',
  // 'no-implicit-coercion': 'off',
  // 'no-implicit-globals': 'off',
  'no-implied-eval': 'error',
  // 'no-invalid-this': 'off',
  'no-iterator': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-loop-func': 'off',
  //'no-magic-numbers': 'off',
  'no-multi-spaces': 'error',
  'no-multi-str': 'error',
  'no-new': 'off',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  // 'no-octal': 'off',
  'no-octal-escape': 'error',
  'no-param-reassign': 'error',
  'no-proto': 'error',
  // 'no-redeclare': 'off',
  'no-restricted-properties': 'error',
  'no-return-assign': 'off',
  // 'no-return-await': 'error',
  'no-script-url': 'error',
  // 'no-self-assign': 'off',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-throw-literal': 'error',
  // 'no-unmodified-loop-condition': 'off',
  'no-unused-expressions': 'error',
  // 'no-unused-labels': 'off',
  // 'no-useless-call': 'off',
  'no-useless-concat': 'error',
  'no-useless-escape': 'warn',
  'no-useless-return': 'error',
  //'no-void': 'off',
  'no-warning-comments': 'off',
  'no-with': 'error',
  'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
  'radix': 'error',
  'require-await': 'warn',
  'vars-on-top': 'error',
  'wrap-iife': ['error', 'outside'],
  'yoda': 'error',

  // strict
  // 'strict': 'off',

  // Variables
  // 'init-declarations': 'off',
  // 'init-declarations': 'off',
  // 'no-delete-var': 'off',
  'no-label-var': 'error',
  'no-restricted-globals': 'error',
  // 'no-shadow': 'off',
  // 'no-shadow-restricted-names': 'off',
  // 'no-undef': 'off',
  'no-undef-init': 'error',
  // 'no-undefined': 'off',
  'no-unused-vars': 'warn',
  'no-use-before-define': 'error',

  // Node.js and CommonJS
  // 'callback-return': 'off',
  'global-require': 'off',
  'handle-callback-err': ['error', '^.*(e|E)rr(or)?$'],
  // 'no-mixed-requires': 'off',
  // 'no-new-require': 'off',
  // 'no-path-concat': 'off',
  // 'no-process-env': 'off',
  // 'no-process-exit': 'off',
  // 'no-restricted-modules': 'off',
  // 'no-sync': 'off',

  // Stylistic Issues
  'array-bracket-spacing': 'error',
  'block-spacing': ['error', 'never'],
  'brace-style': 'error',
  'camelcase': 'error',
  // 'capitalized-comments': 'off',
  "comma-dangle": ["error", {
      "arrays": "ignore",
      "objects": "ignore",
      "imports": "ignore",
      "exports": "ignore",
      "functions": "ignore"
  }],
  'comma-spacing': 'error',
  //'comma-style': 'off',
  'computed-property-spacing': 'error',
  // 'consistent-this': 'off',
  'eol-last': 'error',
  'func-call-spacing': 'error',
  'func-name-matching': 'error',
  // 'func-names': 'off',
  // 'func-style': 'off',
  // 'id-blacklist': 'off',
  // 'id-length': 'off',
  // 'id-match': 'off',
  'indent': ["error", 2],
  // 'jsx-quotes': 'off',
  'key-spacing': 'error',
  'keyword-spacing': 'error',
  'line-comment-position': 'error',
  // 'linebreak-style': 'off',
  'lines-around-comment': ['error', { allowBlockStart: true }],
  // 'lines-around-directive': 'off',
  // 'max-depth': 'off',
  // 'max-len': 'off',
  // 'max-lines': 'off',
  // 'max-nested-callbacks': 'off',
  // 'max-params': 'off',
  // 'max-statements': 'off',
  // 'max-statements-per-line': 'off',
  // 'multiline-ternary': 'off',
  'new-cap': 'error',
  'new-parens': 'error',
  // 'newline-after-var': 'off',
  // 'newline-before-return': 'off',
  // 'newline-per-chained-call': 'off',
  'no-array-constructor': 'error',
  // 'no-bitwise': 'off',
  // 'no-continue': 'off',
  'no-inline-comments': 'error',
  // 'no-lonely-if': 'off',
  // 'no-mixed-operators': 'off',
  // 'no-mixed-spaces-and-tabs': 'off',
  'no-multi-assign': 'error',
  // 'no-multiple-empty-lines': 'off',
  // 'no-negated-condition': 'off',
  'no-nested-ternary': 'error',
  // 'no-new-object': 'off',
  // 'no-plusplus': 'off',
  // 'no-restricted-syntax': 'off',
  // 'no-tabs': 'off',
  // 'no-ternary': 'off',
  'no-trailing-spaces': 'error',
  'no-underscore-dangle':  ['error', { allowAfterThis: true }],
  'no-unneeded-ternary': 'error',
  'no-whitespace-before-property': 'error',
  'nonblock-statement-body-position': 'error',
  // 'object-curly-newline': 'off',
  // 'object-curly-spacing': 'off',
  // 'object-property-newline': 'off',
  // 'one-var': 'off',
  // 'one-var-declaration-per-line': 'off',
  // 'operator-assignment': 'off',
  // 'operator-linebreak': 'off',
  'padded-blocks': ['error', 'never'],
  // 'quote-props': 'off',
  'quotes': ['error', 'single', { avoidEscape: true }],
  // 'require-jsdoc': 'off',
  'semi': ['error', 'never'],
  'semi-spacing': 'error',
  // 'sort-keys': 'off',
  // 'sort-vars': 'off',
  'space-before-blocks': 'error',
  'space-before-function-paren': ['error', { anonymous: 'never', named: 'never' }],
  'space-in-parens': 'error',
  'space-infix-ops': 'error',
  'space-unary-ops': 'error',
  'spaced-comment': 'error',
  'template-tag-spacing': ['error', 'always'],
  'unicode-bom': 'error',
  'wrap-regex': 'off',

  // ECMAScript 6
  'arrow-body-style': 'error',
  'arrow-parens': ['error', 'as-needed'],
  'arrow-spacing': 'error',
  // 'constructor-super': 'off',
  'generator-star-spacing': 'error',
  // 'no-class-assign': 'off',
  'no-confusing-arrow': 'error',
  // 'no-const-assign': 'off',
  // 'no-dupe-class-members': 'off',
  'no-duplicate-imports': 'error',
  // 'no-new-symbol': 'off',
  // 'no-restricted-imports': 'off',
  // 'no-this-before-super': 'off',
  'no-useless-computed-key': 'error',
  'no-useless-constructor': 'error',
  // 'no-useless-rename': 'off',
  'no-var': 'error',
  'object-shorthand': ['error', 'always', { avoidQuotes: true }],
  'prefer-arrow-callback': 'error',
  'prefer-const': ['error', { ignoreReadBeforeAssign: true }],
  'prefer-destructuring': ['warn', { 'object': true, 'array': false }],
  'prefer-numeric-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  // 'require-yield': 'off',
  'rest-spread-spacing': 'error',
  // 'sort-imports': 'off',
  // 'symbol-description': 'off',
  'template-curly-spacing': 'error',
  'yield-star-spacing': ['error', 'before'],
};
